
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


ASSETS_PATH = Path(r"./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1600x900")
window.configure(bg="#001910")
window.title("HashCrack API Client")


canvas = Canvas(
    window,
    bg="#001910",
    height=900,
    width=1600,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    496.5,
    276.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1),
    state="disabled"
)
entry_1.place(
    x=19.0,
    y=8.0,
    width=955.0,
    height=534.0
)

canvas.create_text(
    15.0,
    554.0,
    anchor="nw",
    text="Your API Key",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    227.5,
    596.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_2.place(
    x=25.0,
    y=584.0,
    width=405.0,
    height=23.0
)

canvas.create_text(
    1239.0,
    20.0,
    anchor="nw",
    text="Add/Check\nHash",
    fill="#FFFFFF",
    font=("Quicksand Medium", 20 * -1),
    justify="center"
)

canvas.create_text(
    990.0,
    61.12103271484375,
    anchor="nw",
    text="Hash",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1290.0,
    100.87578868865967,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_3.place(
    x=1000.0,
    y=89.0,
    width=580.0,
    height=25.229299545288086
)

canvas.create_text(
    532.0,
    618.0,
    anchor="nw",
    text="Hash",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    831.0,
    667.6149997711182,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_4.place(
    x=542.0,
    y=654.0,
    width=578.0,
    height=25.229999542236328
)

canvas.create_text(
    990.0,
    125.38217163085938,
    anchor="nw",
    text="Format",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    1090.0,
    165.1369276046753,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_5.place(
    x=1000.0,
    y=151.52227783203125,
    width=180.0,
    height=25.229299545288086
)

canvas.create_text(
    1207.0,
    628.0,
    anchor="nw",
    text="Format",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    1307.0,
    667.754786491394,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_6.place(
    x=1216.0,
    y=656.5,
    width=180.0,
    height=25.229299545288086
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1453.0,
    y=136.0,
    width=116.0,
    height=58.0
)

canvas.create_text(
    1255,
    269.0,
    anchor="nw",
    text="Get File",
    fill="#FFFFFF",
    font=("Quicksand Medium", 20 * -1),
    justify="center"
)

canvas.create_rectangle(
    1004.0,
    280.5,
    1237.0,
    280.5,
    fill="#FFFFFF",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1261.0,
    y=136.0,
    width=116.0,
    height=58.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1040.0,
    y=316.0,
    width=200.0,
    height=75.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1369.0,
    y=787.0,
    width=200.0,
    height=76.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=956.0,
    y=790.0,
    width=200.0,
    height=75.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=542.0,
    y=791.0,
    width=200.0,
    height=75.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=1350.0,
    y=316.0,
    width=200.0,
    height=75.0
)

canvas.create_text(
    1213.0,
    570.0,
    anchor="nw",
    text="Cracking Threads\nManagement",
    fill="#FFFFFF",
    font=("Quicksand Medium", 20 * -1),
    justify="center"
)

canvas.create_rectangle(
    508.0,
    568.0,
    508.0,
    876.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    532.0,
    700.0,
    anchor="nw",
    text="ID",
    fill="#FFFFFF",
    font=("Quicksand Medium", 16 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    594.5,
    739.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#3A3939",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Quicksand Medium", 16 * -1)
)
entry_7.place(
    x=542.0,
    y=728.0,
    width=105.0,
    height=25.0
)

canvas.create_rectangle(
    1004.0,
    47.5,
    1237.0,
    47.5,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1347.0,
    280.5,
    1580.0,
    280.5,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1347.0,
    47.5,
    1580.0,
    47.5,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    528.5,
    600.5,
    1214.5,
    600.5,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1378.0,
    600.5,
    1580.0,
    600.5,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
